### ISSUE TITLE
how to make changes in existing GitHub repository in local code editor  

### ISSUE THREAD

**Issue by Akanksha10029** [Akanksha10029/Django_python#1]
kindly provide codes like git init... or something like this

**Comment by Prashant29062003** [comment]
Open the Repository in Your Code Editor: Open your code editor (such as VS Code) and open the folder where you cloned the repository.
Try to write in terminal:
~code .
then ~git add .
~git commit -m "Your descriptive commit message"

**Comment by Akanksha10029** [comment]
Thank you so much
